name: Build

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest # Install and cache required apt packages
      with:
        packages: build-essential cmake
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build library
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
    - name: Run tests
      run: |
        cd build
        make CTEST_OUTPUT_ON_FAILURE=1 test
